"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("./react");
exports.React = React;
var h_1 = require("./h");
exports.h = h_1.h;
var fragment_1 = require("./fragment");
exports.fragment = fragment_1.fragment;
var render_1 = require("./render");
exports.render = render_1.render;
